apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipline-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipline-pod
  template:
    metadata:
      labels:
        app: pipline-pod
    spec:
      containers:
        - name: pipline
          image: 192.168.204.201:8888/kiwi/demo:v11
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: pipline-service
  namespace: dev
spec:
  selector:
    app: pipline-pod
  type: NodePort
  ports:
    - port: 30002
      targetPort: 8080
